# Generated by Django 4.2.11 on 2024-07-08 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_item_birthdate_item_birthplace_item_citizenship_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='birthdate',
        ),
        migrations.RemoveField(
            model_name='item',
            name='citizenship',
        ),
        migrations.RemoveField(
            model_name='item',
            name='city_municipality',
        ),
        migrations.RemoveField(
            model_name='item',
            name='height_cm',
        ),
        migrations.RemoveField(
            model_name='item',
            name='primary_level',
        ),
        migrations.RemoveField(
            model_name='item',
            name='secondary_level',
        ),
        migrations.RemoveField(
            model_name='item',
            name='tertiary_level',
        ),
        migrations.RemoveField(
            model_name='item',
            name='weight_kg',
        ),
        migrations.RemoveField(
            model_name='item',
            name='zipcode',
        ),
        migrations.AddField(
            model_name='item',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='birthday',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='nationality',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='primary',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='secondary',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='tertiary',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='civil_status',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='gender',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='phone',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='height_CM',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='weight_KG',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
